{
  "swagger": "2.0",
  "host": "waiviodev.com/",
  "schemes": [
    "https"
  ],
  "info": {
    "version": "0.0.1",
    "title": "Waivio auth service",
    "description": "Documentation for waivio auth service"
  },
  "basePath": "auth/",
  "paths": {
    "/facebook": {
      "post": {
        "tags": [
          "Auth"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "access_token",
            "in": "body",
            "description": "facebook access_token",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User data",
            "examples": {
              "data": {
                "user": "user data"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/beaxy": {
      "post": {
        "tags": [
          "beaxyAuth"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "params",
            "description": "Auth by beaxy(if authBy - credentials => use {user: , password: } in authData. 2fa=> {token2fa: , code: , user: })",
            "required": false,
            "schema": {
              "$ref": "#/definitions/auth_beaxy"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "2fa auth needed",
            "schema": {
              "example": {
                  "code": 321,
                  "response": "TWO_FA_VERIFICATION_NEEDED",
                  "payload": {
                    "token2fa": "0fce19045e0f460c9943c586f6117fdc"
                  }
              }
            }
          },
          "201": {
            "description": "success (code 200!!!)",
            "headers": {
              "access-token": {
                "type": "string",
                "description": "access-token"
              },
              "expires-in": {
                "type": "number"
              },
              "um_session": {
                "description": "um-session cookies",
                "type": "string"
              }
            },
            "schema": {
              "example": {
                "user": {
                  "_id": "5e4e91b73b3102381e41d037",
                  "objects_follow": [],
                  "users_follow": [],
                  "json_metadata": "{\"profile\":{\"name\":\"investarena\",\"profile_image\":null}}",
                  "wobjects_weight": 0,
                  "count_posts": 0,
                  "last_posts_count": 0,
                  "name": "bxy_",
                  "alias": "investarena",
                  "createdAt": "2020-02-20T14:03:35.632Z",
                  "updatedAt": "2020-02-20T14:46:47.921Z",
                  "__v": 0
                },
                "payload": {
                  "crmToken": "fghfghgfhfhgfhdg",
                  "sessionId": "476b0205-4b75-4696-b584-82c2761efe10",
                  "stompUser": "gfhdgfhdgfhhdgfhdfghdfhfsd",
                  "stompPassword": "sdfdsfdsfdsfdsfsgdfg"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "example": {
                "message": "2fa token not provided"
              }
            }
          }
        }
      }
    },
    "/beaxy_keepalive": {
      "get": {
        "tags": [
          "beaxyAuth"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "sid",
            "in": "query",
            "description": "beaxy session ID",
            "type": "string",
            "required": true
          },
          {
            "name": "um_session",
            "in": "headers",
            "description": "session cookies",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "result",
            "schema": {
              "example": {
                  "result": "Ok"
              }
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
            "example": {
                  "message": "Not found"

              }
            }
          }
        }
      }
    },
    "/instagram": {
      "post": {
        "tags": [
          "Auth"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "access_token",
            "in": "body",
            "description": "instagram access_token",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User data",
            "examples": {
              "data": {
                "user": "user data"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/google": {
      "post": {
        "tags": [
          "Auth"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "access_token",
            "in": "body",
            "description": "google access_token",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User data",
            "examples": {
              "data": {
                "user": "user data"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/validate_auth_token": {
      "post": {
        "tags": [
          "Auth"
        ],
        "produces": [
          "application/json"
        ],
        "description": "Send access-token in headers. Auth headers are: 'access-token, expires-in, waivio-auth",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "user access_token",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User data with auth headers",
            "schema": {
              "$ref": "#/definitions/validateToken"
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/refresh_auth_token": {
      "post": {
        "tags": [
          "Auth"
        ],
        "produces": [
          "application/json"
        ],
        "description": "Send access-token in headers. Auth headers are: 'access-token, expires-in, waivio-auth",
        "parameters": [
          {
            "name": "refresh-token",
            "in": "header",
            "description": "user refresh_token",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "result with auth headers",
            "schema": {
              "$ref": "#/definitions/refreshToken"
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/hive/challenge": {
      "get": {
        "tags": [
          "HiveAuth"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "username",
            "in": "query",
            "description": "Hive account requesting a nonce",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a one-time nonce",
            "schema": {
              "$ref": "#/definitions/hiveChallengeResponse"
            }
          },
          "400": {
            "description": "Invalid username",
            "schema": {
              "$ref": "#/definitions/hiveError"
            }
          },
          "5xx": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/hiveError"
            }
          }
        }
      }
    },
    "/login-keychain": {
      "post": {
        "tags": [
          "HiveAuth"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Signature payload produced by Hive Keychain",
            "schema": {
              "$ref": "#/definitions/hiveLoginRequest"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "JWT issued",
            "schema": {
              "$ref": "#/definitions/hiveLoginResponse"
            }
          },
          "400": {
            "description": "Nonce missing/expired/invalid signature format",
            "schema": {
              "$ref": "#/definitions/hiveError"
            }
          },
          "403": {
            "description": "Signature not authorized",
            "schema": {
              "$ref": "#/definitions/hiveError"
            }
          }
        }
      }
    },
    "/hive/me": {
      "get": {
        "tags": [
          "HiveAuth"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "Bearer <jwt> issued by /login-keychain",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Decoded JWT payload",
            "schema": {
              "$ref": "#/definitions/hiveMeResponse"
            }
          },
          "401": {
            "description": "Token missing/invalid",
            "schema": {
              "$ref": "#/definitions/hiveError"
            }
          }
        }
      }
    },
    "/hive/metrics": {
      "get": {
        "tags": [
          "HiveAuth"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "x-api-key",
            "in": "header",
            "description": "Optional API key if configured on the server",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "Aggregated auth counters",
            "schema": {
              "$ref": "#/definitions/hiveMetricsResponse"
            }
          },
          "403": {
            "description": "Missing/invalid API key",
            "schema": {
              "$ref": "#/definitions/hiveError"
            }
          }
        }
      }
    },
    "/guest_operations": {
      "post": {
        "tags": [
          "Operation"
        ],
        "produces": [
          "application/json"
        ],
        "description": "Transport to waivio services guest actions",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "user access_token",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "body",
            "description": "action type key",
            "type": "string",
            "required": true
          },
          {
            "name": "data",
            "in": "body",
            "description": "data of request",
            "type": "string",
            "required": true
          },
          {
            "name": "userName",
            "in": "body",
            "description": "user name",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "any_status": {
            "description": "Any data from services",
            "examples": {
              "data": {
                "user": "user data"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/has_social_account": {
      "get": {
        "tags": [
          "Auth"
        ],
        "produces": [
          "application/json"
        ],
        "description": "Check demo user authorize",
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "description": "id of social account",
            "type": "string",
            "required": true
          },
          {
            "name": "provider",
            "in": "query",
            "description": "user provider",
            "type": "string",
            "enum": ["facebook", "google"],
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "examples": {
              "data": {
                "user": "user data"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "refreshToken": {
      "type": "object",
      "example": {
        "result": true
      }
    },
    "validateToken": {
      "type": "object",
      "example": {
          "user": {
            "provider": "google",
            "_id": "5ef32cbdf01bb831a4c61725",
            "objects_follow": [],
            "users_follow": [],
            "json_metadata": "{\"profile\":{\"name\":\"\",\"profile_image\":null,\"email\":null}}",
            "posting_json_metadata": "{\"profile\":{\"name\":\"\",\"profile_image\":null,\"email\":null}}",
            "wobjects_weight": 0,
            "count_posts": 0,
            "last_posts_count": 0,
            "last_posts_counts_by_hours": [],
            "followers_count": 0,
            "name": "waivio_oleg",
            "alias": "",
            "createdAt": "2020-06-24T10:36:45.313Z",
            "updatedAt": "2020-06-24T10:36:45.313Z",
            "__v": 0
          }
        }
    },
    "hiveChallengeResponse": {
      "type": "object",
      "example": {
        "nonce": "3ab4d0b54f3de4f3d86e9073d3698898b754bb8ff1337bd5223c54cb6a9c79a2",
        "username": "someuser",
        "expiresIn": 300
      }
    },
    "hiveLoginRequest": {
      "type": "object",
      "required": [
        "username",
        "nonce",
        "signature"
      ],
      "properties": {
        "username": {
          "type": "string"
        },
        "nonce": {
          "type": "string"
        },
        "signature": {
          "type": "string",
          "description": "Hex encoded signing result from Hive Keychain"
        },
        "publicKey": {
          "type": "string",
          "description": "Optional public key echo from Keychain (ignored by backend)"
        }
      }
    },
    "hiveLoginResponse": {
      "type": "object",
      "example": {
        "token": "<jwt>",
        "tokenType": "Bearer",
        "expiresIn": 3600,
        "expiresAt": 1731231231,
        "username": "someuser",
        "loginMethod": "hive_keychain"
      }
    },
    "hiveMeResponse": {
      "type": "object",
      "example": {
        "username": "someuser",
        "loginMethod": "hive_keychain",
        "exp": 1731231231,
        "iat": 1731227631
      }
    },
    "hiveMetricsResponse": {
      "type": "object",
      "example": {
        "challenge": {
          "total": 10,
          "success": 9,
          "failures": {
            "invalid_username": 1
          }
        },
        "login": {
          "total": 6,
          "success": 4,
          "failures": {
            "invalid_nonce": 1,
            "signature_not_authorized": 1
          }
        }
      }
    },
    "hiveError": {
      "type": "object",
      "example": {
        "error": "invalid_nonce",
        "message": "Nonce not found"
      }
    },
    "auth_beaxy": {
      "type": "object",
      "properties": {
        "authBy": {
          "type": "string",
          "enum": ["2fa", "credentials"]
        },
        "authData": {
          "type": "object",
          "properties": {
            "token2fa": {
              "type": "string"
            },
            "code": {
              "type": "number"
            },
            "user": {
              "type": "string"
            },
            "password": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
